### ISSUE TITLE
Differences from bloc library

### ISSUE THREAD

**Issue by chimon2000** [RedBrogdon/rebloc#10]
On the service, @felangel's [bloc](https://github.com/felangel/bloc) library seems to have a very similar api and intent.  Wondering what some of the differences are?

**Comment by redbrogdon** [comment]
Good question.

Both this package and that one (assuming you grab flutter_bloc with it) provide a set of classes to manage state within an application. as well as a collection of widgets designed to propagate state information down the widget tree and input events back up in response. They also both use Dart streams to pass data around.

The main difference, really, is that Rebloc uses a Redux-like pattern for managing the flow of information, and bloc uses the BLoC pattern. There are not, as I understand it, actions, middleware, or reducers in bloc as they exist in rebloc. Bloc also uses the term state in a different way, and is designed to house app state in multiple places rather than a single, monolithic object as Rebloc does.

None of these differences make either library better or worse, at least in my mind. They're just two different patterns with different plusses and minuses.

**Comment by felangel** [comment]
Yes, I completely agree with @RedBrogdon 👍
