### ISSUE TITLE
Dispatch an action from the context of extended SimpleBloc

### ISSUE THREAD

**Issue by mbn18** [RedBrogdon/rebloc#12]
Hi,

In my `bloc` class I listen to location event. How can I dispatch an action on each event?

    class TrackingBloc extends SimpleBloc<AppState> {
        ...
        bg.BackgroundGeolocation.onLocation((bg.Location location) {
            dispatcher(DoSomethinWithLocation(location));
        }
        ...
    }

**Comment by redbrogdon** [comment]
Thanks for asking. There are a couple ways you can do it, depending on whether you prefer `SimpleBloc` or `Bloc`

If you're using `SimpleBloc` (and it looks like you are), you can define some Actions that look like this:

* BeginMonitoringLocation
* LocationUpdated
* EndMonitoringLocation

When your SimpleBloc's middleware receives a BeginMonitoringLocation action, it can store the dispatcher it gets in [`middleware`](https://github.com/RedBrogdon/rebloc/blob/master/lib/src/engine.dart#L158) and use it later to dispatch LocationUpdated actions with the new location information whenever `onLocation` fires.

If you're using `Bloc`, you can do something similar with the same actions. Instead of using the dispatcher method, you'd just use [asyncExpand](https://api.dartlang.org/stable/2.1.0/dart-async/Stream/asyncExpand.html) to add new LocationUpdated actions directly to the stream. I rarely have a need for `asyncExpand`, but I always feel fancy using it. 😄

**Comment by mbn18** [comment]
Thanks Andrew, seems to work as expected.
If any one interested, here is the implementation:

```dart
class TrackingBloc extends SimpleBloc<AppState> {

  @override
  Action middleware(dispatcher, state, action) {
    ...
    if (action is StartLocationListenersAction) {
      LocationListener(dispatcher);
      return action;
    }
    return action;
  }

  AppState reducer(state, action) {
    ...
    return state;
  }
}

class LocationListener {
  LocationListener(DispatchFunction dispatcher) {
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      dispatcher(LocationUpdatedAction(location));
    });
  }
}
```
