### ISSUE TITLE
Missing post-reducer middleware functionality

### ISSUE THREAD

**Issue by josvos** [RedBrogdon/rebloc#4]
Nice redesign of the redux ideas. I've been doing something similar (still WIP), but with blocs keeping their state as an *accumulated* state in a stream, using the stream's `scan()` to call its reducer.

What seems to be missing in rebloc, but what I used frequently with react-redux in the past, is the ability to execute middleware functions *after* the reducer(s) have changed the state.  For example, after changing the state you may want to perform some external actions, like logging, sending a network message about the finished action (MQTT in my case), etc. In react-redux, everything after `next(action)` in the middleware function could do this.

Wondering whether you could think about how to add this functionality in some way to rebloc.

**Comment by redbrogdon** [comment]
You've hit on a weakness in the original design, which I stumbled onto when I wanted to cache the app state in [voxxedapp](https://github.com/devoxx/voxxedapp) to local storage after receiving a completed network request. I had an Action like this:

```dart
class RefreshedConferenceAction extends Action {
  final Conference conference;
  RefreshedConferenceAction(this.conference);
}
```

The normal place for a side effect like saving to storage would be middleware, but as you've pointed out, the action needs to be reduced first, otherwise I'm caching stale data.

I solved this in the short term by adding `afterward` to the Action class:

```dart
abstract class Action {
  Action _next;

  Action();

  void afterward(Action a) {
    if (_next == null) {
      _next = a;
    } else {
      _next.afterward(a);
    }
  }

  factory Action.cancelled() => _CancelledAction();
}
```

This lets me "schedule" a new Action to be dispatched after the current one has finished reducing. In my middleware I can thus return this:

```dart
return currentAction..afterward(SaveAppStateAction());
```

The listener at the end of the reduce Stream checks to see if an action that's just completed has an "afterward" action, and puts it into the dispatch sink if it does:

```dart
reducerStream.listen((a) {
  assert(a.state != null);
  states.add(a.state);
  if (a.action._next != null) {
    dispatcher(a.action._next);
  }
});
```

I don't know if this is that great a solution, though. It makes the Actions mutable to an extent, which I don't like. It also complicates things like swallowing actions (since any "afterward" actions would also get swallowed, which could cause some unexpected and subtle bugs between Blocs).

Now that I'm considering all this again, what do you think about having *two* opportunities to apply middleware, both before and after the reducing step? Rather than "middleware," I'd end up with "preware" and "postware," so to speak. Each Bloc would then have a chance to apply before-reducer side effects, then reduce, then apply post-reducer side effects.

**Comment by jogboms** [comment]
>    Now that I'm considering all this again, what do you think about having two opportunities to apply middleware, both before and after the reducing step? Rather than "middleware," I'd end up with "preware" and "postware," so to speak. Each Bloc would then have a chance to apply before-reducer side effects, then reduce, then apply post-reducer side effects.

@RedBrogdon This would be a good addition to what `rebloc` already is.

**Comment by redbrogdon** [comment]
Just pushed version 0.2.0 to the repo. It expands the `Bloc` interface to offer three opportunities to interact with the dispatch stream: middleware, reducer, and "afterware." Afterware are executed after all the reducers have had their chance, and allow Blocs to perform side effects with the post-reducer app state.

**Comment by redbrogdon** [comment]
I should mention this also removes the entire `afterward` scheme that was previously added to deal with this issue and is no longer necessary. So it's a breaking change.
